#will work on centos7 or RHEL7 
---
- name: repeat jobs
  hosts: nodeone.example.com
  tasks:
    - name: create some users and assign different passwords
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
      loop:
        - name: gabbar
          password: "{{ 'samba' | password_hash('sha512') }}"

        - name: basanti
          password: "{{ 'dhanno' | password_hash('sha512') }}"
